### ISSUE TITLE
pagination.jade not working

### ISSUE THREAD

**Issue by shinux** [tcrowe/generator-hexo-theme#11]
I just replace all of `.jade` files with `.pug`, and replace the plugin `hexo-renderer-jade` to `hexo-renderer-pug`.

most of the templates work well, except `pagination`, it rendered as the raw content.

**Comment by tcrowe** [comment]
Thank you @shinux. I'll take a look at this soon. I'm in the process of moving here.

**Comment by tcrowe** [comment]
I just learned that jade is now pug. So we can make a PR converting those and fixing the broken templates.

**Comment by tcrowe** [comment]
A pug version was submitted here https://github.com/tcrowe/generator-hexo-theme/pull/13 It's now in the most recent package.
