### ISSUE TITLE
Archive / index pagination doesn't work

### ISSUE THREAD

**Issue by jbreckmckye** [tcrowe/generator-hexo-theme#15]
If I create a skeleton theme using this tool, I cannot move between archive pages - routes like `/page/2` are just duplicates of the first page.

Repro case:
- install generator-hexo-theme on Windows 10
- create a dummy theme named 'test', using all the default CLI configs
- add eleven or more post files
- run `hexo serve` or `hexo generate`

![image](https://user-images.githubusercontent.com/3148617/32701750-fd02368c-c7d2-11e7-81c2-3817adb8f396.png)
![image](https://user-images.githubusercontent.com/3148617/32701755-068f2e30-c7d3-11e7-86b7-d3bb24c1a5e6.png)

**Comment by tcrowe** [comment]
Thanks for the detailed issue. That does help. Do you know if it matters which template engine?

**Comment by tcrowe** [comment]
I found two bugs from this.

`site.posts` should be `page.posts`
https://github.com/tcrowe/generator-hexo-theme/blob/master/app/templates/layout-ejs/partials/recent-posts.ejs#L2

Pagination include can be replaced with `<%-paginator()%>`
https://github.com/tcrowe/generator-hexo-theme/blob/master/app/templates/layout-ejs/index.ejs#L3

**Comment by tcrowe** [comment]
`generator-hexo-theme@0.5.0` includes the hexo helper `paginator` rather than using the older custom one.

I'm going to migrate the themes over to a `slush` project which I linked on the readme.

If you think this is fixed you can let me know or close it out.

**Comment by jbreckmckye** [comment]
Alright, I'll use those template fixes and let you know how it goes.

**Comment by jbreckmckye** [comment]
Hooray! Those fixes work just great.
