### ISSUE TITLE
Confusing message about paginator.

### ISSUE THREAD

**Issue by diaosj** [tcrowe/generator-hexo-theme#19]
Following the ReadMe, I run these commands as below:
```bash
npm install yo -g
npm install generator-hexo-theme -g

npm install hexo-renderer-ejs -g
npm install hexo-renderer-njks -g
npm install hexo-render-pug -g

npm install hexo-renderer-stylus -g
npm install hexo-renderer-less -g
npm install hexo-renderer-sass -g

yo hexo-theme
```

The generated directory tree is like:
├── _config.yml
├── layout
│   ├── archive.pug
│   ├── category.pug
│   ├── includes
│   │   ├── layout.pug
│   │   └── recent-posts.pug
│   ├── index.pug
│   ├── page.pug
│   ├── post.pug
│   └── tag.pug
└── source
    ├── css
    │   └── blanco.styl
    ├── favicon.ico
    └── js
        └── blanco.js

Then I apply this newly-generated theme and run hexo server. But the index page shows a wrong message: 
![image](https://user-images.githubusercontent.com/5987721/71086755-9765c000-21d5-11ea-8a81-f65d0218a324.png)

I checked the document. It seems to relate to paginator? Maybe something like 'paginator.pug' is missing?

**Comment by tcrowe** [comment]
Hi @diaosj 👋 

It is confusing because we have to create the hexo project first:

```sh
mkdir my-site
cd my-site
hexo init
```

The renderer plugins can go in side there. Only after creating the hexo project can we then go into the themes.

```sh
cd themes
mkdir my-theme
cd my-theme
yo hexo-theme
```

Does that help or did you already do that?

**Comment by diaosj** [comment]
Ah, I have created the hexo project, otherwise, the `hexo g` command shouldn't work.

**Comment by tcrowe** [comment]
I'm not sure if the renderer plugins can be in the theme or if they have to be in the root. I think they go in the root though.

**Comment by tcrowe** [comment]
A few people have said this. It could probably be more clear.

Another thing is that some newer hexo modules have come out. Maybe this can be updated.

**Comment by diaosj** [comment]
After selecting all the three 'other technical features', I run `hexo clean` command and met this error.

![image](https://user-images.githubusercontent.com/5987721/71141466-2e229300-224f-11ea-8250-457202d87e01.png)

Actually I think your readme is clear enough. Easy to understand & follow. It's just out of my ability to handle this unexpected situation.

"The repo". Do you mean the theme I generated? Ok, I'll upload it to github. Minutes later.

**Comment by tcrowe** [comment]
Preferably the whole `./blog/*` directory. We'll solve this. I just did a test locally and it worked. I think we can find the config problem.

**Comment by diaosj** [comment]
Hi Tony, here's the repo: https://github.com/diaosj/hexo-theme-blanco
I uploaded all the files generated by `yo`.

**Comment by tcrowe** [comment]
> Hi Tony, here's the repo: https://github.com/diaosj/hexo-theme-blanco
> I uploaded all the files generated by `yo`.

I'll pull this and test

**Comment by diaosj** [comment]
> Preferably the whole `./blog/*` directory. We'll solve this. I just did a test locally and it worked. I think we can find the config problem.

Sorry, I just saw this. I'll upload the whole blog directory to another repo.

**Comment by tcrowe** [comment]
<img width="499" alt="Screen Shot 2019-12-18 at 8 22 27 PM" src="https://user-images.githubusercontent.com/1634015/71142283-28d43280-21d4-11ea-9211-f537ea0ef335.png">


I pulled your theme and tested it out.

I removed that readme which broke it. `rm themes/blanco/scripts/readme.md`

Then clean and serve

```sh
hexo clean
hexo server --debug
```

**Comment by tcrowe** [comment]
In the main blog directory I only installed `hexo-renderer-pug`

**Comment by tcrowe** [comment]
This file is confusing and this generator probably should not add it. `scripts/readme.md`

**Comment by diaosj** [comment]
I removed file `scripts/readme.md`, but the website page stayed the same:

> extends includes/layout.pug block content include includes/recent-posts.pug #paginator!= paginator()

My `hexo` version is 4.1.1. Not sure if the version is related.

My `./blog/*` directory is pushed to this repo: https://github.com/diaosj/hexo-blog-demo

**Comment by diaosj** [comment]
The website just echoes the content of the file `layout/index.pug`. Missing the transformation from `.pug` to `.html`.

**Comment by diaosj** [comment]
> The website just echoes the content of the file `layout/index.pug`. Missing the transformation from `.pug` to `.html`.

Realizing this, I googled the usage of pug and found that I need to install pug first... 

```bash
npm install pug
```

It works.

Every unexpected behavior roots in a stupid mistake.

**Comment by tcrowe** [comment]
I'm glad you got it working but I think it is still something else.

```
hexo-renderer-pug
hexo-render-pug
```

Sometimes these modules get confused. They both have `pug` in them.

https://github.com/hexojs/hexo-renderer-pug/blob/master/package.json#L31
https://github.com/maxknee/hexo-render-pug/blob/master/package.json#L20

**Comment by diaosj** [comment]
I didn't notice that these two modules are different until you pointed this out. Interesting.

I work as a backend engineer mainly. Frontend codes, ahhhhh, a challenge for me.
