### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by kane-thornwyrd** [tcrowe/generator-hexo-theme#3]
Node 0.10.29
Windows 7 64bits

Console: https://gist.github.com/kane-thornwyrd/7df9f83e3438e5dc7a08

**Comment by tcrowe** [comment]
Published version 0.2.1 to npm

Thank you

**Comment by kane-thornwyrd** [comment]
You're welcome ! Albeit being small, its a handy generator to have, I came to Hexo because it's easy and fast to hack and push to prod, this generator follow the very same trend :smiley: .

**Comment by tcrowe** [comment]
I'm glad it could help with your theming. Do you have any ideas to help improve it?
