### ISSUE TITLE
Swig support?

### ISSUE THREAD

**Issue by ozkxr** [tcrowe/generator-hexo-theme#4]
Could be possible to add swig support to this generator?

#SFME

**Comment by tcrowe** [comment]
Sorry, I had notifications off but I've turned them back on.

**Comment by tcrowe** [comment]
I haven't forgotten about this and I think it's a good idea. I think it should be done but I'm struggling to find the time right now.

**Comment by ozkxr** [comment]
Could I help coding and making a PR?

**Comment by tcrowe** [comment]
Yes, and thanks for discussing even though this thread has been slow.

**Comment by ozkxr** [comment]
Don't worry :rocket:

**Comment by ozkxr** [comment]
@tcrowe 

I found that [Swig is no ~~longer~~ currently mantained](https://github.com/paularmstrong/swig).

Swig is a Jinja2-based template engine. Another one is [Nunjucks](https://mozilla.github.io/nunjucks/) which is maintained by Mozilla.

So what do you think about support Nunjucks instead?

**Comment by tcrowe** [comment]
I think that is good.

Nunjucks and Swig are somehow built into the hexo core module:
[https://github.com/hexojs/hexo/search?utf8=%E2%9C%93&q=nunjucks](https://github.com/hexojs/hexo/search?utf8=%E2%9C%93&q=nunjucks)
[https://github.com/hexojs/hexo/search?utf8=%E2%9C%93&q=swig&type=Code](https://github.com/hexojs/hexo/search?utf8=%E2%9C%93&q=swig&type=Code)

**Comment by tcrowe** [comment]
Swig added. Check out the new commit.

**Comment by ozkxr** [comment]
Thank you. Thank you very much.

I feel bad because I really wanted to help with this, but I didn't.

I will check the commit and the query and will let you know if I can improve the code.

I think, we could close this issue now right?

Good, job. Thanks again.

**Comment by tcrowe** [comment]
It was a part of a bigger update I did where I upgraded to the newest versions of yeoman and the associated test tools. Making the swig part was like copying the EJS layout and trying to figure out Swig syntax. It's a pretty neat template language!
