### ISSUE TITLE
how do I fire up server or generate?

### ISSUE THREAD

**Issue by cleechtech** [tcrowe/generator-hexo-theme#6]
When I try to run `hexo server` or `hexo generate` I get:

```
$ hexo generate
Usage: hexo <command>

Commands:
  help     Get help on Hexo.
  init     Create a new Hexo folder.
  version  Display version information.
...
```

I tried running `npm install hexo-server --save` but I still cannot fire up the server or compile the blog code. What am I missing?

**Comment by cleechtech** [comment]
hmm breaking changes perhaps? https://github.com/hexojs/hexo/wiki/Breaking-Changes-in-Hexo-3.0 What needs to be modified?

**Comment by tcrowe** [comment]
I was just thinking about that. This was designed during approximately hexo version 2.8. I'd like to upgrade it soon. It might just be a version bump.

**Comment by tcrowe** [comment]
You might want to try this again. I put in an update today.

**Comment by cleechtech** [comment]
Still nothing. How do I start a server? Also there's no package.json

![screen shot 2016-01-18 at 12 27 17 pm](https://cloud.githubusercontent.com/assets/3578908/12401975/de63de4c-bdde-11e5-9530-4ffb7410b4cd.png)

**Comment by cleechtech** [comment]
```
$ hexo --version
hexo-cli: 0.1.8
os: Darwin 15.2.0 darwin x64
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1p
```

**Comment by tcrowe** [comment]
I was able to get a full run-through of making the blog, then making a theme. Here goes:

```
npm install hexo-cli@latest -g
npm install yo@latest -g
npm install generator-hexo-theme@latest -g
mkdir blogtest
cd blogtest
hexo init
cd themes
mkdir themetest
cd themetest
yo hexo-theme
# edit _config.yml
cd ../..
# edit _config.yml, change theme: themetest
hexo server --debug
```
<img width="322" alt="screen shot 2016-01-18 at 1 37 01 pm" src="https://cloud.githubusercontent.com/assets/1634015/12402238/e39357b2-bde8-11e5-8b9b-349aa8bf3013.png">

**Comment by tcrowe** [comment]
It's unstyled when you start out. The Stylus or other CSS can be edited from the source or theme source directory.

<img width="403" alt="screen shot 2016-01-18 at 1 41 03 pm" src="https://cloud.githubusercontent.com/assets/1634015/12402270/0cfcbed6-bde9-11e5-9062-a2049f03f5a4.png">

**Comment by cleechtech** [comment]
lol ok thank you. I though this generator would make a full project. Did not know I had to also use the hexo-cli to initially fire up a project. I submitted #7 to clear this up moving forwards!
